add auto-update option to ax configure, add easy upgrading go

diff --git a/interact/axiom-configure b/interact/axiom-configure
--- a/interact/axiom-configure
+++ b/interact/axiom-configure
@@ -24,8 +24,56 @@ echo '
  "𝓶𝓲𝓰𝓱𝓽 𝓪𝓼 𝔀𝓮𝓵𝓵 𝓫𝓮 𝓪𝔁𝓲𝓸𝓶: 𝓽𝓱𝓮 𝓭𝔂𝓷𝓪𝓶𝓲𝓬 𝓲𝓷𝓯𝓻𝓪𝓼𝓽𝓻𝓾𝓬𝓽𝓾𝓻𝓮 𝓯𝓻𝓪𝓶𝓮𝔀𝓸𝓻𝓴 𝓯𝓸𝓻 𝓮𝓿𝓮𝓻𝔂𝓫𝓸𝓭𝔂! - @𝓹𝓻𝔂0𝓬𝓬 @0𝔁𝓽𝓪𝓿𝓲𝓪𝓷" 
  "𝓪𝓵𝓻𝓲𝓰𝓱𝓽, 𝔂𝓸𝓾 𝓰𝓸𝓽 𝓶𝓮, 𝓲𝓽𝓼 𝓳𝓾𝓼𝓽 𝓪𝔁𝓲𝓸𝓶: 𝓽𝓱𝓮 𝓭𝔂𝓷𝓪𝓶𝓲𝓬 𝓲𝓷𝓯𝓻𝓪𝓼𝓽𝓻𝓾𝓬𝓽𝓾𝓻𝓮 𝓯𝓻𝓪𝓶𝓮𝔀𝓸𝓻𝓴 𝓯𝓸𝓻 𝓮𝓿𝓮𝓻𝔂𝓫𝓸𝓭𝔂! - @𝓹𝓻𝔂0𝓬𝓬 @0𝔁𝓽𝓪𝓿𝓲𝓪𝓷"
  "𝓼𝓽𝓸𝓵𝓮𝓷 𝓯𝓻𝓸𝓶: 𝓪𝔁𝓲𝓸𝓶: 𝓽𝓱𝓮 𝓭𝔂𝓷𝓪𝓶𝓲𝓬 𝓲𝓷𝓯𝓻𝓪𝓼𝓽𝓻𝓾𝓬𝓽𝓾𝓻𝓮 𝓯𝓻𝓪𝓶𝓮𝔀𝓸𝓻𝓴 𝓯𝓸𝓻 𝓮𝓿𝓮𝓻𝔂𝓫𝓸𝓭𝔂! - @𝓹𝓻𝔂0𝓬𝓬 @0𝔁𝓽𝓪𝓿𝓲𝓪𝓷"
- ' | xargs shuf -n1 -e 
+ ' | xargs shuf -n1 -e
 echo ''
+
+###########################################################################################################
+# manage auto-update settings
+#
+manage_auto_update() {
+    auto_update_one_liner='[ $[ $RANDOM % 16 ] == 0 ] && $HOME/.axiom/interact/axiom-update >> /dev/null 2>&1'
+
+    # Check if auto_update is explicitly set
+    if [ -z "${auto_update+x}" ]; then
+        # Loop until a valid response is given
+        while true; do
+            echo -e -n "${BYellow}Do you want to periodically update axiom automatically in the background (recommended)? y/n: \n>> ${Color_Off}"
+            read acc
+
+            if [[ "$acc" == "y" ]] || [[ "$acc" == "yes" ]]; then
+                auto_update="yes"
+                break
+            elif [[ "$acc" == "n" ]] || [[ "$acc" == "no" ]]; then
+                auto_update="no"
+                break
+            else
+                echo -e "${BRed}Invalid response. Please enter 'y' for yes or 'n' for no.${Color_Off}"
+            fi
+        done
+    fi
+
+    # If auto_update is true, add the auto_update_one_liner if it's not already present
+    if [[ "$auto_update" == "yes" ]]; then
+        if ! grep -Fq "$auto_update_one_liner" "$AXIOM_PATH/interact/includes/vars.sh"; then
+            echo "$auto_update_one_liner" >> "$AXIOM_PATH/interact/includes/vars.sh"
+            echo "Auto-update has been enabled."
+        else
+            echo "Auto-update is already enabled."
+        fi
+    # If auto_update is false, remove the auto_update_one_liner if present
+    elif [[ "$auto_update" == "no" ]]; then
+        if grep -Fq "$auto_update_one_liner" "$AXIOM_PATH/interact/includes/vars.sh"; then
+            # Use grep and sed to remove the line from the file
+            grep -vF "$auto_update_one_liner" "$AXIOM_PATH/interact/includes/vars.sh" > "$AXIOM_PATH/interact/includes/vars_tmp.sh"
+            mv "$AXIOM_PATH/interact/includes/vars_tmp.sh" "$AXIOM_PATH/interact/includes/vars.sh"
+            echo "Auto-update has been disabled."
+        else
+            echo "Auto-update is already disabled."
+        fi
+    else
+        echo "Invalid value for auto_update. Please use 'yes' or 'no'."
+    fi
+}
 
 ###########################################################################################################
 # Shell setup functions
@@ -36,8 +84,9 @@ function bash_shell(){
     cp "$HOME"/.bashrc "$HOME"/.bashrc-$timestamp >> /dev/null 2>&1
 
     if [[ "$unattended" == "true" ]]; then
-     echo -e "${BGreen}Installing Golang 1.22.2${Color_Off}"
-     wget -q https://golang.org/dl/go1.22.2.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz && rm go1.22.2.linux-amd64.tar.gz
+     echo -e "${BGreen}Installing Golang ${GolangVersion}${Color_Off}"
+     sudo rm -rf /usr/local/go/ >> /dev/null 2>&1
+     wget -q https://golang.org/dl/go${GolangVersion}.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go${GolangVersion}.linux-amd64.tar.gz && rm go${GolangVersion}.linux-amd64.tar.gz
      mkdir -p "${HOME}/go"
      export GOPATH=$HOME/go
      export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
@@ -51,11 +100,12 @@ function bash_shell(){
      echo "[[ -f ~/.bashrc ]] && . ~/.bashrc" >> "${HOME}"/.bash_profile
      source ~/.bashrc  >> /dev/null 2>&1
     else
-     echo -e -n "${BYellow}Do you want to install Golang 1.22.2? y/n: \n>> ${Color_Off}"
+     echo -e -n "${BYellow}Do you want to install Golang ${GolangVersion}? y/n: \n>> ${Color_Off}"
      read acc
      if [[ "$acc" == "y" ]]; then
-      echo -e "${BGreen}Installing Golang 1.22.2${Color_Off}"
-      wget -q https://golang.org/dl/go1.22.2.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz && rm go1.22.2.linux-amd64.tar.gz
+      echo -e "${BGreen}Installing Golang ${GolangVersion}${Color_Off}"
+      sudo rm -rf /usr/local/go/ >> /dev/null 2>&1
+      wget -q https://golang.org/dl/go${GolangVersion}.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go${GolangVersion}.linux-amd64.tar.gz && rm go${GolangVersion}.linux-amd64.tar.gz
       mkdir -p "${HOME}/go"
       export GOPATH=$HOME/go
       export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
@@ -87,8 +137,9 @@ function zsh_shell(){
     cp "$HOME"/.zshrc "$HOME"/.zshrc-$timestamp >> /dev/null 2>&1
 
     if [[ "$unattended" == "true" ]]; then
-     echo -e "${BGreen}Installing Golang 1.22.2${Color_Off}"
-     wget -q https://golang.org/dl/go1.22.2.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz && rm go1.22.2.linux-amd64.tar.gz
+     echo -e "${BGreen}Installing Golang ${GolangVersion}${Color_Off}"
+     sudo rm -rf /usr/local/go/ >> /dev/null 2>&1
+     wget -q https://golang.org/dl/go${GolangVersion}.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go${GolangVersion}.linux-amd64.tar.gz && rm go${GolangVersion}.linux-amd64.tar.gz
      mkdir -p "${HOME}/go"
      export GOPATH=$HOME/go
      export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
@@ -100,11 +151,12 @@ function zsh_shell(){
      source "${HOME}"/.zshrc >> /dev/null 2>&1
      SHELL=$(which zsh)
     else
-     echo -e -n "${BYellow}Do you want to install Golang 1.22.2? y/n: \n>> ${Color_Off}"
+     echo -e -n "${BYellow}Do you want to install Golang ${GolangVersion}? y/n: \n>> ${Color_Off}"
      read acc
      if [[ "$acc" == "y" ]]; then
-      echo -e "${BGreen}Installing Golang 1.22.2${Color_Off}"
-      wget -q https://golang.org/dl/go1.22.2.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz && rm go1.22.2.linux-amd64.tar.gz
+      echo -e "${BGreen}Installing Golang ${GolangVersion}${Color_Off}"
+      sudo rm -rf /usr/local/go/ >> /dev/null 2>&1
+      wget -q https://golang.org/dl/go${GolangVersion}.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go${GolangVersion}.linux-amd64.tar.gz && rm go${GolangVersion}.linux-amd64.tar.gz
       mkdir -p "${HOME}/go"
       export GOPATH=$HOME/go
       export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
@@ -135,8 +187,9 @@ function omz_shell(){
     sudo apt install zsh zsh-syntax-highlighting zsh-autosuggestions -y
     sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
     if [[ "$unattended" == "true" ]]; then
-     echo -e "${BGreen}Installing Golang 1.22.2${Color_Off}"
-     wget -q https://golang.org/dl/go1.22.2.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz && rm go1.22.2.linux-amd64.tar.gz
+     echo -e "${BGreen}Installing Golang ${GolangVersion}${Color_Off}"
+     sudo rm -rf /usr/local/go/ >> /dev/null 2>&1
+     wget -q https://golang.org/dl/go${GolangVersion}.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go${GolangVersion}.linux-amd64.tar.gz && rm go${GolangVersion}.linux-amd64.tar.gz
      mkdir -p "${HOME}/go"
      export GOPATH=$HOME/go
      export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
@@ -148,11 +201,12 @@ function omz_shell(){
      source "${HOME}"/.zshrc >> /dev/null 2>&1
      SHELL=$(which zsh)
     else
-     echo -e -n "${BYellow}Do you want to install Golang 1.22.2? y/n: \n>> ${Color_Off}"
+     echo -e -n "${BYellow}Do you want to install Golang ${GolangVersion}? y/n: \n>> ${Color_Off}"
      read acc
      if [[ "$acc" == "y" ]]; then
-      echo -e "${BGreen}Installing Golang 1.22.2${Color_Off}"
-      wget -q https://golang.org/dl/go1.22.2.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz && rm go1.22.2.linux-amd64.tar.gz
+      echo -e "${BGreen}Installing Golang ${GolangVersion}${Color_Off}"
+      sudo rm -rf /usr/local/go/ >> /dev/null 2>&1
+      wget -q https://golang.org/dl/go${GolangVersion}.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go${GolangVersion}.linux-amd64.tar.gz && rm go${GolangVersion}.linux-amd64.tar.gz
       mkdir -p "${HOME}/go"   
       export GOPATH=$HOME/go
       export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
@@ -193,6 +247,8 @@ function usage() {
         echo -e "    Avoid any promots, defaults to Oh My Zsh unless --shell argument is also provided"
         echo -e "  --shell <bash, zsh, omz (Oh My Zsh)> (optional)"
         echo -e "    Add axiom to path, backup .zshrc/.bashrc to .zshrcbak/.bashrcbak"
+        echo -e "  --auto-update <yes, no> (optional)"
+        echo -e "    Toggle auto-update to periodically update axiom"
         echo -e "  --debug (optional)"
         echo -e "    Enable debug mode (VERY VERBOSE!)"
         echo -e "  --help"
@@ -200,7 +256,7 @@ function usage() {
 }
 
 ###########################################################################################################
-# Parse command line arguments 
+# Parse command line arguments
 #
 i=0
 for arg in "$@"
@@ -208,69 +264,91 @@ do
     i=$((i+1))
     if [[  ! " ${pass[@]} " =~ " ${i} " ]]; then
         set=false
-        if [[ "$arg" == "--config" ]]; then
+       if [[ "$arg" == "--config" ]]; then
             n=$((i+1))
             config=$(echo ${!n})
             config_flag="true"
             set=true
             pass+=($i)
             pass+=($n)
-        fi
+       fi
        if [[ "$arg" == "--debug" ]]; then
             set -xv
             set=true
             pass+=($i)
-        fi
+       fi
+       if [[ "$arg" == "--auto-update" ]]; then
+            n=$((i+1))
+            auto_update=$(echo ${!n})
+            auto_update_flag="true"
+            set=true
+            pass+=($i)
+            pass+=($n)
+       fi
        if [[ "$arg" == "--setup" ]]; then
             setup=true
             set=true
             pass+=($i)
-        fi
-        if [[ "$arg" == "--unattended" ]]; then
-            unattended=true          
+       fi
+       if [[ "$arg" == "--unattended" ]]; then
+            unattended=true
             set=true
             pass+=($i)
-        fi
-        if [[ "$arg" == "--shell" ]]; then
+       fi
+       if [[ "$arg" == "--shell" ]]; then
             n=$((i+1))
             usershell=$(echo ${!n})
             set=true
             pass+=($i)
             pass+=($n)
-        fi
-        if [[ "$arg" == "--help" ]] || [[ "$arg" == "-h" ]] || [[ "$arg" == "help" ]]; then
+       fi
+       if [[ "$arg" == "--help" ]] || [[ "$arg" == "-h" ]] || [[ "$arg" == "help" ]]; then
             usage
             exit
             set=true
             pass+=($i)
-        fi
+       fi
 fi
 done
 
 if [[ "$setup" != "true" ]]; then
-usage 
+usage
 exit
-
 fi
 
+if [ ! -d "$AXIOM_PATH" ]; then
+    echo -e "${BGreen}Installing Ax scripts...${Color_Off}"
+    git clone https://github.com/attacksurge/ax "$AXIOM_PATH"
+    AXIOM_PATH="$HOME/.axiom"
+     source "$AXIOM_PATH/interact/includes/vars.sh"
+else
+    cd "$AXIOM_PATH" && git pull
+fi
 
 if [ ! -z ${unattended:+x} ]; then
-echo -e "${BGreen}Hello! Welcome to the Ax Framework configuration :)"
-echo -e "${Green}Detected unattended option passed from command line...${Color_Off}"
-echo -e "${BGreen}Automatically installing dependencies and begining installation!${Color_Off}"
-if [ -z ${usershell:+x} ]; then
-usershell="omz"
+ echo -e "${BGreen}Hello! Welcome to the Ax Framework configuration :)"
+ echo -e "${Green}Detected unattended option passed from command line...${Color_Off}"
+ echo -e "${BGreen}Automatically installing dependencies and begining installation!${Color_Off}"
+ if [ -z ${usershell:+x} ]; then
+  usershell="omz"
+ fi
+ if [ -z ${auto_update:+x} ]; then
+  auto_update="yes"
+  manage_auto_update
+ else
+  manage_auto_update
 fi
+
 elif [ ! -z ${config+x} ]; then
-echo -e "${BGreen}Hello! Welcome to the Ax Framework configuration :)"
-echo -e "${Green}Detected axiom.json option passed from command line...${Color_Off}"
-echo -e "${BGreen}Automatically installing dependencies and begining installation!${Color_Off}"
+ echo -e "${BGreen}Hello! Welcome to the Ax Framework configuration :)"
+ echo -e "${Green}Detected axiom.json option passed from command line...${Color_Off}"
+ echo -e "${BGreen}Automatically installing dependencies and begining installation!${Color_Off}"
 else
-echo -e "${BGreen}Hello! Welcome to the Ax Framework configuration :)"
-echo -e "Press enter to install dependencies and begin installation!${Color_Off}"
-read
-echo -e "${BGreen}INSTALLING THE AX FRAMEWORK...${Color_Off}"
-sleep 1
+ echo -e "${BGreen}Hello! Welcome to the Ax Framework configuration :)"
+ echo -e "Press enter to install dependencies and begin installation!${Color_Off}"
+ read
+ echo -e "${BGreen}INSTALLING THE AX FRAMEWORK...${Color_Off}"
+ sleep 1
 fi
 
 echo -e "${BWhite}Installing deps! Please wait :) ${Color_Off}"
@@ -319,7 +397,7 @@ if [[ $BASEOS == "Linux" ]]; then
         sudo rm -fr /tmp/interlace
         git clone https://github.com/codingo/Interlace.git /tmp/interlace
         cd /tmp/interlace && sudo python3 setup.py install
-        
+ 
     elif [[ $OS == "Ubuntu" ]] || [[ $OS == "Debian" ]] || [[ $OS == "Linuxmint" ]] || [[ $OS == "Parrot" ]] || [[ $OS == "Kali" ]] || [[ $OS == "unknown-Linux" ]] || [[ $OS == "UbuntuWSL" ]]; then
        if ! command -v sudo &> /dev/null; then
         export DEBIAN_FRONTEND=noninteractive
@@ -369,18 +447,18 @@ if [[ $BASEOS == "Mac" ]]; then
          brew install jq
          echo -e "${BGreen}Installing coreutils...${Color_Off}"
          brew install coreutils
-         echo "source $HOME/.axiom/interact/includes/ax-completion.sh" >> ~/.zshrc 
+         echo "source $HOME/.axiom/interact/includes/ax-completion.sh" >> ~/.zshrc
          if [[ "$unattended" == "true" ]]; then
           echo -e "${BGreen}Installing Python3...${Color_Off}"
           brew install python3
           echo -e "${BGreen}Installing setuptools...${Color_Off}"
           pip3 install setuptools --break-system-packages
           echo -e "${BGreen}Installing go...${Color_Off}"
-          brew install golang 
+          brew install golang
         else
           echo -e -n "${BYellow}Do you want to upgrade Python (brew install python3) y/n: \n>> ${Color_Off}"
           read acc
-          if [[ "$acc" == "y" ]]; then 
+          if [[ "$acc" == "y" ]]; then
            echo -e "${BGreen}Installing Python3...${Color_Off}"
            brew install python3
 	  fi
@@ -443,17 +521,7 @@ fi
 fi
 
 ###########################################################################################################
-# Clone Ax repo
-#
-if [ ! -d "$AXIOM_PATH" ]; then
-    echo -e "${BGreen}Installing Ax scripts...${Color_Off}"
-    git clone https://github.com/attacksurge/ax "$AXIOM_PATH"
-else
-    cd "$AXIOM_PATH" && git pull
-fi
-
-###########################################################################################################
-# unattended setup flag logic 
+# unattended setup flag logic
 #
 if [ -z ${config:+x} ]; then
 if [[ "$unattended" == "true" ]]; then
@@ -461,13 +529,14 @@ echo "Unattended setup"
 mkdir  -p "$HOME"/.axiom/accounts/
 
 else
+
 ###########################################################################################################
 # Default setup logic ( e.g. when --unattended and --config args are not used
 #
 mkdir -p "${HOME}/.axiom/tmp/"
+manage_auto_update
 echo -e "${BGreen}Configuring your cloud account...${Color_Off}"
 "$AXIOM_PATH"/interact/axiom-account-setup
-
 
 ###########################################################################################################
 # If axiom_rsa doesnt exist, create the SSH key and add to it Packer Builder and axiom.json
@@ -484,21 +553,22 @@ else
  jq '.sshkey="'axiom_rsa'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"  >> /dev/null 2>&1
  cat ~/.ssh/axiom_rsa.pub >"$AXIOM_PATH"/configs/authorized_keys
 fi
-fi 
+fi
 
 else
+
 ###########################################################################################################
 # Config parsing logic
 #
  echo "Parsing config passed from command line"
 
  mkdir  -p "$HOME"/.axiom/accounts/
- 
+
  if test -f "$config"; then
 
   provider="$(cat "$config" | jq -r '.provider')"
   account=${provider}$(date +%s)
-  cp "$config" "$HOME"/.axiom/accounts/"$account".json  
+  cp "$config" "$HOME"/.axiom/accounts/"$account".json
 
  else
 
@@ -508,14 +578,14 @@ else
   echo "$config" > "$HOME"/.axiom/axiom.json
   echo -e "${BGreen}Cloud account configuration passed from command line...${Color_Off}"
  fi
-fi 
+fi
 export PATH="$PATH:$HOME/.axiom/interact"
 
 if [[ $unattended == "true" ]] ; then
 echo -e "${BWhite}Ax Framework install complete. Run ax account-setup to use!...${Color_Off}"
 echo -e "${BWhite}You may need to restart your shell: $SHELL${Color_Off}"
 if [[ $config_flag == "true" ]] ; then
-"$HOME"/.axiom/interact/axiom-account "$account"  
+"$HOME"/.axiom/interact/axiom-account "$account"
 fi
 exit 0
 fi
@@ -530,3 +600,4 @@ else
 echo -e "${BWhite}You may need to restart your shell: $SHELL${Color_Off}"
 "$HOME"/.axiom/interact/axiom-account "$account"
 fi
+
diff --git a/interact/axiom-fleet b/interact/axiom-fleet
--- a/interact/axiom-fleet
+++ b/interact/axiom-fleet
@@ -40,13 +40,14 @@ cycle_regions=false
 region_array=()
 gen_name=""
 provider="$(jq -r ".provider" "$AXIOM_PATH/axiom.json")"
-image_name="$(jq -r '.imageid' "$AXIOM_PATH"/axiom.json)"
+image="$(jq -r '.imageid' "$AXIOM_PATH"/axiom.json)"
 region="$(jq -r '.region' "$AXIOM_PATH"/axiom.json)"
 image_id=""
 instances=false
 time=320
 init_timeout=4
 init_sleep=4
+manual_image_id=false
 
 ###########################################################################################################
 # DO Region Transfer
@@ -58,7 +59,7 @@ if [[ "$provider" == "do" ]]; then
  requested_image_id_regions="$regionargs"
  if [[ "$avail_image_id_regions" != *"$requested_image_id_regions"* ]]; then
   echo -e "${Color_Off}]"
-  echo -e "${BYellow}instance ${BGreen}"$name"${BYellow} requested image in region ${BRed}$regionargs${BYellow}, however image ${BRed}$image_name${BYellow} only exists in ${BRed}$(echo $avail_image_id_regions | tr '\n' ',')"
+  echo -e "${BYellow}instance ${BGreen}"$name"${BYellow} requested image in region ${BRed}$regionargs${BYellow}, however image ${BRed}$image${BYellow} only exists in ${BRed}$(echo $avail_image_id_regions | tr '\n' ',')"
   echo -e "${BYellow}axiom will attempt to transfer image to new region, this can take a few minutes please be patient...${Color_Off}"
   doctl compute image-action transfer $image_id --region $regionargs --wait
    if [ $? -eq 0 ]; then
@@ -139,11 +140,18 @@ do
         fi
         if [[ "$arg" == "--image" ]] ; then
             n=$((i+1))
-            image_name=$(echo ${!n})
+            image=$(echo ${!n})
             set=true
             pass+=($i)
             pass+=($n)
 	fi
+        if [[ "$arg" == "--image-id" ]]; then
+            n=$((i+1))
+            manual_image_id=$(echo ${!n})
+            set=true
+            pass+=($i)
+            pass+=($n)
+        fi
         if  [[ "$set" != "true" ]]; then
             space=" "
             if [[ $arg =~ $space ]]; then
@@ -178,16 +186,38 @@ if [[ "$provider" == "linode" ]]; then
  init_sleep=6
 fi
 
+###########################################################################################################
+# Get image_id from $image ( default is from axiom.json ) or from user supplied manual image id param
+#
+if [ "$manual_image_id" != "false" ]
+then
+    image_id="$manual_image_id"
+else
+    image_id="$(get_image_id "$image")"
+    if [ -z "$image_id" ]; then
+        echo -e "${BRed}ERROR: image ${Color_Off}[ ${BBlue}$image ${Color_Off}]${BRed} not found. you may need to run ${Color_Off}[ ${BBlue}axiom-build --setup ${Color_Off}]${BRed} to build a new image."
+        echo -e "${BRed}if you've already built an image, list all images with ${Color_Off}[ ${BBlue}axiom-images ls ${Color_Off}]${BRed} and select it with ${Color_Off}[ ${BBlue}axiom-images select \$image_name${Color_Off}]"
+        echo -e "${BRed}exiting...${Color_Off}"
+        exit 1
+    fi
+fi
 
 ###########################################################################################################
-# Get image_id from $image ( default is from axiom.json ) or from user supplied --image param 
+# Check if ssh key is specified in axiom.json
 #
-image_id="$(get_image_id "$image_name")"
-if [ -z "$image_id" ]; then
-  echo -e "${BRed}Image $image_name not found in $region. Do you need to run 'axiom-build'?${Color_Off}"
-  echo -e "${BRed}Use 'axiom-image ls' to list all images. Select one with 'axiom-image set \$image_name'${Color_Off}"
-  exit 1
+if [ "$sshkey" == "" ] || [ "$sshkey" == "null" ]; then
+echo -e  "${BYellow}WARNING: sshkey not found in ~/axiom/axiom.json. Adding ${Color_Off}[ ${BBlue}axiom_rsa ${Color_Off}] ${BYellow}key as a backup."
+echo -e  "${BYellow}If ${Color_Off}[ ${BBlue}axiom_rsa ${Color_Off}] ${BYellow}was not used to build the initial image ${Color_Off}[ ${BBlue}$image_id ${Color_Off}]${BYellow}, you may have to manually edit ~/axiom/axiom.json to set the correct sshkey${Color_Off}"
+account_path=$(ls -la "$AXIOM_PATH"/axiom.json | rev | cut -d " " -f 1 | rev)
+ if [ -f ~/.ssh/axiom_rsa ] ; then
+  jq '.sshkey="'axiom_rsa'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"
+
+ else
+  ssh-keygen -b 2048 -t rsa -f ~/.ssh/axiom_rsa -q -N ""
+  jq '.sshkey="'axiom_rsa'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"  >> /dev/null 2>&1
+ fi
 fi
+
 
 ###########################################################################################################
 # Initialize fleet
@@ -196,7 +226,7 @@ if [[ "$cycle_regions" == "false" ]]; then
 
 # Chance to cancel initialization of fleet
 #
-echo -e "${BWhite}Initializing new fleet '${BGreen}$gen_name${BWhite}' with '${BGreen}$amount${BWhite}' instances using image '${BGreen}$image_name${BWhite}' in region '${BGreen}$region${BWhite}'${Color_Off}...${Color_Off}"
+echo -e "${BWhite}Initializing new fleet '${BGreen}$gen_name${BWhite}' with '${BGreen}$amount${BWhite}' instances using image '${BGreen}$image${BWhite}' in region '${BGreen}$region${BWhite}'${Color_Off}...${Color_Off}"
 echo -e "${BWhite}INITIALIZING IN 5 SECONDS, CTRL+C to quit... ${Color_Off}"
 sleep 5
 
@@ -238,7 +268,7 @@ if [[ "$cycle_regions" != "false" ]]; then
 ###########################################################################################################
 # Chance to cancel initialization of fleet
 #
-echo -e "${BWhite}Initializing new fleet '${BGreen}$gen_name${BWhite}' with '${BGreen}$amount${BWhite}' instances using image '${BGreen}$image_name${Color_Off}'...${Color_Off}"
+echo -e "${BWhite}Initializing new fleet '${BGreen}$gen_name${BWhite}' with '${BGreen}$amount${BWhite}' instances using image '${BGreen}$image${Color_Off}'...${Color_Off}"
 echo -e "${BWhite}Cycling through following regions:${BGreen}$cycle_regions${BWhite}...${Color_Off}"
 echo -e "${BWhite}INITIALIZING IN 5 SECONDS, CTRL+C to quit... ${Color_Off}"
 sleep 5
