refactor account-helpers, allow for easy cloud cli version updates

diff --git a/interact/axiom-configure b/interact/axiom-configure
--- a/interact/axiom-configure
+++ b/interact/axiom-configure
@@ -381,7 +381,7 @@ if [[ $BASEOS == "Linux" ]]; then
         sudo rm -fr /tmp/interlace
         git clone https://github.com/codingo/Interlace.git /tmp/interlace
         cd /tmp/interlace && sudo python3 setup.py install
- 
+
     elif [[ $OS == "Ubuntu" ]] || [[ $OS == "Debian" ]] || [[ $OS == "Linuxmint" ]] || [[ $OS == "Parrot" ]] || [[ $OS == "Kali" ]] || [[ $OS == "unknown-Linux" ]] || [[ $OS == "UbuntuWSL" ]]; then
        if ! command -v sudo &> /dev/null; then
         export DEBIAN_FRONTEND=noninteractive
@@ -390,35 +390,42 @@ if [[ $BASEOS == "Linux" ]]; then
         ln -fs /usr/share/zoneinfo/$(curl ipinfo.io/"$ip" | jq -r .timezone) /etc/localtime
         dpkg-reconfigure --frontend noninteractive tzdata
        fi
-        echo -e "${BGreen}Installing fail2ban jq git ruby python3-pip curl iputils-ping net-tools unzip xsltproc bc rsync sudo wget nano bsdmainutils openssh-server...${Color_Off}"
-        DEBIAN_FRONTEND=noninteractive sudo apt-get update && sudo apt-get install git ruby python3-pip curl iputils-ping net-tools unzip xsltproc bc rsync sudo wget nano bsdmainutils openssh-server fail2ban jq -y 
-        echo -e "${BGreen}Installing packer...${Color_Off}"
-        wget -q -O /tmp/packer.zip https://releases.hashicorp.com/packer/1.8.1/packer_1.8.1_linux_amd64.zip && cd /tmp/ && unzip packer.zip && sudo mv packer /usr/bin/ && rm /tmp/packer.zip 
-        echo -e "${BGreen}Installing Interlace...${Color_Off}"
-        sudo rm -fr /tmp/interlace
-        git clone https://github.com/codingo/Interlace.git /tmp/interlace
-        cd /tmp/interlace && sudo python3 setup.py install
+       echo -e "${BGreen}Installing fail2ban jq git ruby python3-pip curl iputils-ping net-tools unzip xsltproc bc rsync sudo wget nano bsdmainutils openssh-server...${Color_Off}"
+       DEBIAN_FRONTEND=noninteractive sudo apt-get update && sudo apt-get install git ruby python3-pip curl iputils-ping net-tools unzip xsltproc bc rsync sudo wget nano bsdmainutils openssh-server fail2ban jq -y 
+       echo -e "${BGreen}Installing packer...${Color_Off}"
+       wget -q -O /tmp/packer.zip https://releases.hashicorp.com/packer/1.8.1/packer_1.8.1_linux_amd64.zip && cd /tmp/ && unzip packer.zip && sudo mv packer /usr/bin/ && rm /tmp/packer.zip 
+       echo -e "${BGreen}Installing Interlace...${Color_Off}"
+       sudo rm -fr /tmp/interlace
+       git clone https://github.com/codingo/Interlace.git /tmp/interlace
+       cd /tmp/interlace && sudo python3 setup.py install
 
-        elif [[ $OS == "Fedora" ]]; then
-        echo -e "${BGreen}Installing fail2ban mmv bc fzf git rubypick python3-pip curl net-tools unzip util-linux...${Color_Off}"
-        sudo dnf update && sudo dnf -y install mmv bc fzf git rubypick python3-pip curl net-tools unzip util-linux fail2ban
-        echo -e "${BGreen}Installing jq...${Color_Off}"
-        sudo wget -q -O /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && sudo chmod +x /usr/bin/jq
-        echo -e "${BGreen}Installing packer...${Color_Off}"
-        wget -O /tmp/packer.zip https://releases.hashicorp.com/packer/1.8.1/packer_1.8.1_linux_amd64.zip && cd /tmp/ && unzip packer.zip && sudo mv packer /usr/bin/ && rm /tmp/packer.zip
-        fi
+    elif [[ $OS == "Fedora" ]]; then
+       echo -e "${BGreen}Installing fail2ban mmv bc fzf git rubypick python3-pip curl net-tools unzip util-linux...${Color_Off}"
+       sudo dnf update && sudo dnf -y install mmv bc fzf git rubypick python3-pip curl net-tools unzip util-linux fail2ban
+       echo -e "${BGreen}Installing jq...${Color_Off}"
+       sudo wget -q -O /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && sudo chmod +x /usr/bin/jq
+       echo -e "${BGreen}Installing packer...${Color_Off}"
+       wget -O /tmp/packer.zip https://releases.hashicorp.com/packer/1.8.1/packer_1.8.1_linux_amd64.zip && cd /tmp/ && unzip packer.zip && sudo mv packer /usr/bin/ && rm /tmp/packer.zip
+    fi
 fi
 
 if [[ $BASEOS == "Mac" ]]; then
-         echo -e "${BGreen}Installing Brew...${Color_Off}"
-         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+         whereis brew
+         if [ ! $? -eq 0 ] || [[ ! -z ${AXIOM_FORCEBREW+x} ]]; then
+          echo -e "${BGreen}Installing brew...${Color_Off}"
+          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+         else
+          echo -e "${BGreen}Checking for brew... already installed, skipping installation.${Color_Off}"
+          echo -e "${BGreen}    Note: You can force brew installation by running${Color_Off}"
+          echo -e '    $ AXIOM_FORCEBREW=yes $HOME/.axiom/interact/axiom-configure'
+         fi
          echo -e 'Setting permissions'
-         sudo chown -R $(whoami) /usr/local/Homebrew
-         sudo chown -R $(whoami) /usr/local/var/homebrew
-         sudo chown -R $(whoami) /usr/local/etc/bash_completion.d /usr/local/lib/pkgconfig /usr/local/share/aclocal /usr/local/share/doc /usr/local/share/info /usr/local/share/locale /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3 /usr/local/share/man/man5 /usr/local/share/man/man7
-         sudo chown -R $(whoami) /usr/local/share/zsh /usr/local/share/zsh/site-functions
-         chmod u+w /usr/local/share/zsh /usr/local/share/zsh/site-functions
-         chmod u+w /usr/local/etc/bash_completion.d /usr/local/lib/pkgconfig /usr/local/share/aclocal /usr/local/share/doc /usr/local/share/info /usr/local/share/locale /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3 /usr/local/share/man/man5 /usr/local/share/man/man7
+         sudo chown -R $(whoami) /usr/local/Homebrew > /dev/null 2>&1
+         sudo chown -R $(whoami) /usr/local/var/homebrew > /dev/null 2>&1
+         sudo chown -R $(whoami) /usr/local/etc/bash_completion.d /usr/local/lib/pkgconfig /usr/local/share/aclocal /usr/local/share/doc /usr/local/share/info /usr/local/share/locale /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3 /usr/local/share/man/man5 /usr/local/share/man/man7 > /dev/null 2>&1
+         sudo chown -R $(whoami) /usr/local/share/zsh /usr/local/share/zsh/site-functions > /dev/null 2>&1
+         chmod u+w /usr/local/share/zsh /usr/local/share/zsh/site-functions > /dev/null 2>&1
+         chmod u+w /usr/local/etc/bash_completion.d /usr/local/lib/pkgconfig /usr/local/share/aclocal /usr/local/share/doc /usr/local/share/info /usr/local/share/locale /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3 /usr/local/share/man/man5 /usr/local/share/man/man7 > /dev/null 2>&1
          echo -e "${BGreen}Installing wget...${Color_Off}"
          brew install wget
          mkdir -p "${HOME}/go"
@@ -600,4 +607,3 @@ else
 echo -e "${BWhite}You may need to restart your shell: $SHELL${Color_Off}"
 "$HOME"/.axiom/interact/axiom-account "$account"
 fi
-
